$(document).ready(function(){

	var quoteArray = ["We are young yet we don’t have a future",
		"Start copying what you love. Copy copy copy copy. At the end of the copy you will find yourself.",
		"<3",
		"Im so Deep",
		"Easy Peasy Lemon Squeezy",
		"There is no angry way to say BUBBLE",
		"It's not the number of breaths we take, but the number of moments that take our breath away.",
		"Life is what happens to you while you're busy making other plans.",
		"You're only as strong as the drinks you mix, the tables you dance on, and the friends you party with",
		"Live for the nights you'll never remember with the friends you'll never forget",
		"Live, laugh, love.",
		"Sing like no one is listening. Love like you've never been hurt. Dance like nobody is watching.",
		"Yesterday is history, tomorrow a mystery and today is a gift. That's why we call it the present.",
		"Keep calm and carry on.",
		"Shoot for the moon. Even if you miss, you'll land among the stars.",
		"You have to kiss a lot of frogs before you find your prince.",
		"Everything happens for a reason.",
		"If life gives you lemons, make lemonade.",
		"You'll find love when you stop looking.",
		"Live every day like it's your last.",
		"It takes more muscles to frown than it does to smile.",
		"Dream as if you'll live forever. Live as if you'll die today.",
		"Real eyes realize real lies.",
		"You miss 100% of the shots you don't take.",
		"Life is not about waiting for the storm to pass. It's about learning to dance in the rain.",
		"You Only Live Once",
		"Nobody Text faster than a pissed off female",
		"Donut give up",
		"Olive you so much",
		"If I wanted to kill myself I would climb your ego and jump to your IQ.",
		"A day without sunshine is like, you know, night.",
		"Stay Hungry, Stay Foolish",
		"Home is where I can feel Ugly and Enjoy it ",
		"Intoxicated by Memories and feelings",
		"Getting lost is never a waste of time.",
		"A day without light is like night", 
		"Stay, Hustle, Focus",
		"Happiness is being Confidently weird",
		"If your not first your last",
		"I dont love your 4ever, I love you 5ever because 4 isn't enough",
		"Fuck Bitches , Get Money",
		"Disregard Women , Aquire Currency",
		"Life is like a fish",
		"Eat, Shit ,Die",
		"On a scale 1 to 10 you're a 9 and I'm the 1 you need",
		"Are you a camera, because everytime I look at you I smile",
		"Friends make the world beautiful",
		"I hope one day you choke on the shit you talk",
		"If you don't want me at my worst, you don't deserve me at my best",
		"You know whats beautiful? read the first word",
		"If you were a chicken, you'd be impeccable.",
		"You have to be odd to be number one",
		"Never look  back unless you're that ass",
		"Are we ever going to be better than this?",
		"Is that a rocket in your pocket?",
		"What we fear doing most is usually what we most need to do",
		"Everyone cares when it’s too late",
		"Trump can suck my dick",
		"The mitochondria is the powerhouse of the cell",
		"our generation's humour is based off of irony. as we age we will become increasingly ironic to the point where complimenting someone is an insult. this is the future. this is us",
		"I know I was a generic dysfunctional child, but I think a lot of people are.",
		"New Year, New Me",
		"Money is just a number",
		"If he's not over 6 foot he's not worth dating",
		"People die if they are killed...",
		"I did it",
		"Winners never sleep",
		"No greater love hath a man than he lay down his faith for a brother",
		"If I was the force, I'd be with you",
		"YODA only one for me",
		"You R2 good to me",
		"cummies cummies cummies all in my tummies",
		"Roses are red ,violets are blue ,I suck at poetry, but I still love you",
		"What the fuck is this BULLSHIT",
		"People don't think the universe be like it is, but it do",
		"There are only 2 Genders",
		"Eating Chicken can make your kid's dick small",
		"FUPA loss 2k17",
		"Fuck off or I'll punch you in the throat -Mahalma Gandhi",
		"Jet fuel can't melt steel beams",
		"Don't say maybe if u want to say no",
		"You must be the change you wish to see in the world",
		"People who give 110% don't understand how percentages work",
		"You're just a memory",
		"Life isn't perfect but your outfit can be",
		"Suns Out Guns Out",
		"Never not chasing a million things I want.",
		"I wasn’t lucky, I deserved it.",
		"Keep smiling because life is a beautiful thing and there’s so much to smile about.",
		"Say Beer Can with a British accent. I just taught you to say Bacon with a Jamaican accent.",
		"If a dentist makes their money from unhealthy teeth, why would I trust a product 4/5 of them recommend?",
		"Friday, my second favorite F word",
		"When i was Rome.. I did what the Romans did.",
		"Sending my selfie to NASA, because I’m a star.",
		"Just because you’re awake doesn’t mean you should stop dreaming.",
		"Life is like a box of chocolate; sometimes you just dig out the good center parts and leave all the undesirable rest to waste.",
		"I can’t really see another squad tryna cross us",
		"I still ride with my day one",
		"Make the most out of tonight, and worry ‘bout it all tomorrow",
		"Sweatpants, hair tied, chillin’ with no makeup on",
		"My greatest pain in life is that I will never be able to see myself perform live.",
		"Nothing in life is promised except death.",
		"If you have the opportunity to play this game of life you need to appreciate every moment. a lot of people don't appreciate the moment until it's passed",
		"George Bush doesn't care about black people.",
		"My music isn’t just music — it’s medicine",
		"People always say that you can't please everybody. I think that's a cop-out. Why not attempt it? 'Cause think of all the people you will please if you try.",
		"I was never really good at anything except for the ability to learn.",
		"Being the richest man in the cemetery doesn't matter to me. Going to bed at night saying we've done something wonderful, that's what matters to me.",
		"Sometimes life is going to hit you in the head with a brick. Don't lose faith.",
		"My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time.",
		"Truth is more interesting than the fiction we are used to",
		"The most dangerous thing you can do in life is play it safe",
		"When something is important enough, you do it even if the odds are not in your favor",
		"Life is not fair, get used to it."
		];

	/**
 		* Returns a random integer between min (inclusive) and max (inclusive)
 		* Using Math.round() will give you a non-uniform distribution!
 	*/
	function getRandomInt(min, max) {
    	return Math.floor(Math.random() * (max - min + 1)) + min;
	}

	$('#submit').click(makeQuote);

	function makeQuote(){
		var randomPosition =  getRandomInt(0,quoteArray.length);
		var quote = quoteArray[randomPosition];
		$('#quote').text(quote);
	}

});